spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
