server:
  port: 8081

spring:
  application:
    name: user-service
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=5m
  cloud:
    loadbalancer:
      cache:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/