server:
  port: 8080

spring:
  application:
    name: order-service
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=5m
  cloud:
    loadbalancer:
      cache:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 1000

resilience4j:
  circuitbreaker:
    instances:
      producer-service:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
